server:
  port: ${env.server.port:8080}
springdoc:
  swagger-ui:
    path: "/doc/swagger-ui/index.html"
  api-docs:
    path: "/doc/api-docs"
spring:
  application:
    name: "Autenticacion"
  devtools:
    add-properties: false
  webflux:
    base-path: "/api"
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
adapters:
  r2dbc:
    host: ${env.r2dbc.host}
    port: ${env.r2dbc.port}
    database: ${env.r2dbc.database}
    schema: ${env.r2dbc.schema}
    username: ${env.r2dbc.username}
    password: ${env.r2dbc.password}
cors:
  allowed-origins: ${env.origins.allowed}
